<a href="https://colab.research.google.com/github/DeanAdrian/Extra/blob/main/AIDA/58090_Lab02__Jabolt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <div align="center">**Lab 02 - Linear Algebra Review**</div> 

| Submitted By:          | Instructor:               |
|------------------------|---------------------------|
| Baluyot, John Michael  | Engr. Dylan Josh D. Lopez |
| Barona, Federico III   |                           | 
| Estocapio, Dean Adrian |                           |
| Garcia, Lance Gabriel  |                           | 

In [ ]:
import numpy as np
import pandas as pd

### Case 4.c


Problem 4.c: Computational Programming (Also Laboratory 2)

Encode Equations 3.1 to 3.4 as the class LRegression wherein:

*   LRegression should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of numpy.array.
*   It should further have methodsreflecting to at least the four (4) aforementioned equations. Each should have a return value.



In [ ]:
class LRegression():
  def __init__(self, dataSet, y_GndTruth, thetaVector):
    self.dataSet = dataSet
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector

  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.dataSet)
    return magnitude

  def getZ(self): ## Eq. 3.1
    self.dataSetT = self.dataSet.transpose()
    self.z = np.dot(self.dataSetT, self.thetaVector)
    return self.z 

  def getActivation (self): ## Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(-self.z))
    return self.activation

  def getLoss(self): ## Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq= (-1*yt)*(np.log(self.activation)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

In [ ]:
X = np.random.random((300,5))*100
theta = np.random.random((300,1))
y = np.random.randint(0,2,(300,1))

In [ ]:
Regression = LRegression(X, y, theta)

In [ ]:
Regression.getVectorMagnitude()

2273.805204206895

In [ ]:
Regression.getZ()

array([[7427.27429284],
       [7409.1063531 ],
       [7226.11200263],
       [7384.77371914],
       [7246.42451025]])

In [ ]:
Regression.getActivation()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
Regression.getLoss()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in multiply


array([[inf, inf, inf, ..., inf, inf, nan],
       [inf, inf, inf, ..., inf, inf, nan],
       [inf, inf, inf, ..., inf, inf, nan],
       [inf, inf, inf, ..., inf, inf, nan],
       [inf, inf, inf, ..., inf, inf, nan]])