<a href="https://colab.research.google.com/github/DeanAdrian/Extra/blob/main/AIDA/58090_Lab02__Jabolt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <div align="center">**Lab 02 - Linear Algebra Review**</div> 

| Submitted By:          | Instructor:               |
|------------------------|---------------------------|
| Baluyot, John Michael  | Engr. Dylan Josh D. Lopez |
| Barona, Federico III   |                           | 
| Estocapio, Dean Adrian |                           |
| Garcia, Lance Gabriel  |                           | 

In [1]:
import numpy as np
import pandas as pd

In [2]:
u = np.array([1,2,3])
v = np.array([4,2,-3])
t = np.array([[1,2,3],
              [1,2,3]])

In [3]:
def vector_magnitude_np(vector):
  magnitude = np.linalg.norm(vector)
  return magnitude

In [4]:
def  vector_magnitude(vector):
  magnitude = 0
  if vector.ndim == 1:
    for values in vector:
      values = values*values
      magnitude = magnitude + values
    magnitude = magnitude**(1/2)
  else:
    for values in vector:
      values = values@values
      magnitude = magnitude + values
    magnitude = magnitude**(1/2)
  return magnitude

In [5]:
vector_magnitude_np(u)

3.7416573867739413

In [6]:
vector_magnitude(u)

3.7416573867739413

### Case 4.c


Problem 4.c: Computational Programming (Also Laboratory 2)

Encode Equations 3.1 to 3.4 as the class LRegression wherein:

*   LRegression should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of numpy.array.
*   It should further have methodsreflecting to at least the four (4) aforementioned equations. Each should have a return value.



In [7]:
class LRegression():
  def __init__(self, dataSet, y_GndTruth, thetaVector):
    self.dataSet = dataSet
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector

  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.dataSet)
    return magnitude

  def getZ(self): ## Eq. 3.1
    self.dataSetT = self.dataSet.transpose()
    self.z = np.dot(self.dataSetT, self.thetaVector)
    return self.z 

  def getActivation (self): ## Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(-self.z))
    return self.activation

  def getLoss(self): ## Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq= (-1*yt)*(np.log(self.activation)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

In [8]:
X = np.random.random((300,5))*100
theta = np.random.random((300,1))
y = np.random.randint(0,2,(300,1))

In [9]:
Regression = LRegression(X, y, theta)

In [10]:
Regression.getVectorMagnitude()

2207.7517063192095

In [11]:
Regression.getZ()

array([[7184.65072419],
       [7019.67805003],
       [6477.65287609],
       [7142.16173266],
       [7045.72261582]])

In [12]:
Regression.getActivation()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [13]:
Regression.getLoss()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in multiply


array([[inf, nan, inf, ..., inf, inf, inf],
       [inf, nan, inf, ..., inf, inf, inf],
       [inf, nan, inf, ..., inf, inf, inf],
       [inf, nan, inf, ..., inf, inf, inf],
       [inf, nan, inf, ..., inf, inf, inf]])